[theme]
primaryColor = "#7F77DD"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F7F5"
textColor = "#262730"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
